/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hospitalsystem;
import java.util.*;
/**
 *
 * @author Jaycee Kristine
 */
public class HospitalData {
    // Add patient after being called. 'id' is generated by caller (HospitalSystem).
    public static void addPatient(Scanner scanner, List<Person> patients, String id, PriorityNumber called) {
        System.out.println("----------------------------------------");
        System.out.println("          ADD PATIENT INFORMATION");
        System.out.println("----------------------------------------");

        System.out.println("Priority Number: " + called.getPriorityNumber());
        System.out.println("Called Patient Name: " + called.getPatientName());
        System.out.println("(You may edit the name below if needed)");

        System.out.print("First Name: ");
        String fname = scanner.nextLine().trim();

        System.out.print("Middle Name: ");
        String mname = scanner.nextLine().trim();

        System.out.print("Last Name: ");
        String lname = scanner.nextLine().trim();

        int age = 0;
        while (true) {
            System.out.print("Age: ");
            try {
                age = Integer.parseInt(scanner.nextLine().trim());
                break;
            } catch (NumberFormatException e) {
                System.out.println("Enter a valid age (number).");
            }
        }

        System.out.print("Sex (M/F): ");
        String sex = scanner.nextLine().trim();

        System.out.print("Birthdate (e.g. 2025-09-01): ");
        String birthdate = scanner.nextLine().trim();

        System.out.print("Birthplace: ");
        String birthplace = scanner.nextLine().trim();

        System.out.print("Contact No.: ");
        String contact = scanner.nextLine().trim();

        System.out.print("Civil Status: ");
        String civilStatus = scanner.nextLine().trim();

        // Create Person and add
        Person p = new Person(id, fname, mname, lname, sex, age, birthdate, birthplace, contact, civilStatus);
        patients.add(p);

        System.out.println("----------------------------------------");
        System.out.println("Patient successfully added with ID: " + id);
        System.out.println("----------------------------------------");
    }
}