/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package hospitalsystem;
import java.util.*;
import java.time.LocalDate;
import java.time.Period;

/**
 *
 * @author Jaycee Kristine
 */
public class HospitalData {
    // Add patient after being called. 'id' is generated by caller (HospitalSystem).
    public static void addPatient(Scanner scanner, List<Person> patients, String id, PriorityNumber called) {
        System.out.println("----------------------------------------");
        System.out.println("          ADD PATIENT INFORMATION");
        System.out.println("----------------------------------------");

        System.out.println("Priority Number: " + called.getPriorityNumber());
        System.out.println("Called Patient Name: " + called.getPatientName());
        System.out.println("(You may edit the name below if needed)");

        System.out.print("First Name: ");
        String fname = scanner.nextLine().trim();

        System.out.print("Middle Name: ");
        String mname = scanner.nextLine().trim();

        System.out.print("Last Name: ");
        String lname = scanner.nextLine().trim();

      // --- Birthdate with automatic age calculation ---
int year, month, day;
while (true) {
    try {
        System.out.print("Birth Year (YYYY): ");
        year = Integer.parseInt(scanner.nextLine().trim());

        System.out.print("Birth Month (1-12): ");
        month = Integer.parseInt(scanner.nextLine().trim());

        System.out.print("Birth Day (1-31): ");
        day = Integer.parseInt(scanner.nextLine().trim());

        break;
    } catch (Exception e) {
        System.out.println("Invalid input. Try again.");
    }
}

LocalDate bdate = LocalDate.of(year, month, day);
LocalDate today = LocalDate.now();
int age = Period.between(bdate, today).getYears();

String birthdate = bdate.toString();

        System.out.print("Sex (M/F): ");
        String sex = scanner.nextLine().trim();

      
        System.out.print("Birthplace: ");
        String birthplace = scanner.nextLine().trim();

        System.out.print("Contact No.: ");
        String contact = scanner.nextLine().trim();

        System.out.print("Civil Status: ");
        String civilStatus = scanner.nextLine().trim();

        // Create Person and add
        Person p = new Person(id, fname, mname, lname, sex, age, birthdate, birthplace, contact, civilStatus);
        patients.add(p);

        System.out.println("----------------------------------------");
        System.out.println("Patient successfully added with ID: " + id);
        System.out.println("----------------------------------------");
    }
}